config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "log_in" ,to:'sessions#new',:as=>"log_in"
  get "sign_in" ,to:'users#new',:as=>"sign_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  root "sessions#new"
  resources:users
  resources:sessions
  resources:projects do 
    collection  do
      delete :"destroyUser"
    end
  end

    resources:bugs

 # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||=User.new
  if user.user_type == "Manager"
    can :manage, :all
  elsif user.user_type == "Developer"
    can :read, :all
    # byebug
    # can :read, Project: {id: user.id}
  elsif user.user_type == "QA"
    can :read ,:all
  end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :user
  belongs_to :project
 validates :title ,:uniqueness=> true
enum typeOf: %i[feature bug]
  enum status_is: %i[New started completed resolved]
end

app/models/project.rb
class Project < ApplicationRecord
    
    has_many :bugs 
    has_many :project_users
    has_many :users ,through: :project_users , dependent: :destroy
    accepts_nested_attributes_for :project_users ,:allow_destroy => true
    validates :name , :description ,:presence =>true ,:uniqueness=>true

end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :user
  belongs_to :project
  accepts_nested_attributes_for :user
end

app/models/user.rb
class User < ApplicationRecord
    # attr_accessible :email, :password, :password_confirmation
    has_many :bugs 
    has_many :project_users
    has_many :projects ,through: :project_users
   accepts_nested_attributes_for :project_users ,  :allow_destroy => true

    enum role: {seller: 0, buyer: 1, admin: 2}

    # ?authentication
    USER_TYPE=['Manager','Q/A',"Developer"]
    attr_accessor :password
    before_save :encrypt_password
    
    validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :email
    validates_uniqueness_of :email
    
    def self.authenticate(email, password)
      user = find_by_email(email)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end
    
    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

#     def current_ability
#   @current_ability ||= Ability.new(current_user)
# end 
# include Authentication 
helper :all
rescue_from CanCan::AccessDenied do |exception|
  flash[:error] = "Access denied."
  # redirect_to projects_url
end

helper_method :current_user
public
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
     
  def index
    @bugs=Bug.all
  end
  def new
  @bugs=Bug.new
      end
    def create
        
        @bugs = Bug.create(bug_params)
        if @bugs.save
          redirect_to bugs_path
        else 
          render "new"
        end
      end
   def show
    @bugs = Bug.find(params[:id])

   end
        def bug_params
          params.require(:bug).permit(:title, :b_type ,:status ,:project_id,:user_id)
        end
  
        def edit
            @bugs = Bug.find(params[:id])
          end
        
          def update
            @bugs=Bug.update(bug_params)
            redirect_to bug_path
       
          end
      def destroy 
        @bugs=Bug.find(params[:id])
        @bugs.destroy
        redirect_to bugs_path
      end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    load_and_authorize_resource
  
    def index
      
      if params[:q].present?
      @projects=Project.where("name = ?",params[:q])
      else
        # @project=Project.all
        @projects = Project.accessible_by(current_ability)
      end
    #  @projects= @projects.project_users

      authorize! :read, @projects
     

  end

  def show
    @projects = Project.find(params[:id])
   
  end

  def new
    @projects = Project.new

    @projects.project_users.new
    
    # @project=Project.new
    authorize!  :create ,@projects
   
    end

  def create
  
    @projects = Project.create(project_params)
    
    if @projects.save
      redirect_to projects_path
    else
      render action: "new" ,status: :unprocessable_entity
    end
  end

  def edit
    @projects= Project.find(params[:id])
    unauthorize! if cannot? :update ,@projects
  end

  def update
    @projects = Project.find(params[:id])

    if @projects.update(project_params)
      redirect_to projects_path
    else
      render action: "edit",status: :unprocessable_entity
    end

  end

  def destroy 
    @projects = Project.find(params[:id]) 
   
   @user = @projects.users

    if @user
       @projects.users.destroy(@user)
       @projects.destroy
       redirect_to project_path
    end  
    unauthorize! if cannot? :destroy ,@user

  end
  def destroyUser 
    @projects = Project.find(params[:id]) 
    @user = @projects.users
    @projects.users.destroy(@user)
  end

  protected
  def project_params
    params.require(:project).permit(:name,:description,:Bugable,:project_users_attributes => [:project_id ,:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      session[:user_type]=user.user_type
      redirect_to projects_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new" 
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_authorization_check :only => [:create]

  def new
    @user= User.new
  end
  def index
    @user=User.all
  
  end
  def create
    @user=User.create(user_params)
    if @user.save
      
    redirect_to projects_path
    else
      render "new",status: :unprocessable_entity
    end
  end
  def show
    @users=User.find(params[:id])
    
  end

 
  public
  def user_params
    params.require(:user).permit(:name,:email,:password ,:password_confirmation ,:user_type)
  end 
  helper_method :current_user
  public
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
# def link_to_add_fields(name = nil, f = nil, association = nil, options = nil, html_options = nil, &block)
#   # If a block is provided there is no name attribute and the arguments are
#   # shifted with one position to the left. This re-assigns those values.
#   f, association, options, html_options = name, f, association, options if block_given?

#   options = {} if options.nil?
#   html_options = {} if html_options.nil?

#   if options.include? :locals
#     locals = options[:locals]
#   else
#     locals = { }
#   end

#   if options.include? :partial
#     partial = options[:partial]
#   else
#     partial = association.to_s.singularize + '_fields'
#   end

#   # Render the form fields from a file with the association name provided
#   new_object = f.object.class.reflect_on_association(product_user).klass.new
#   fields = f.fields_for(association, new_object, child_index: 'new_record') do |builder|
#     render(partial, locals.merge!( f: builder))
#   end

#   # The rendered fields are sent with the link within the data-form-prepend attr
#   html_options['data-form-prepend'] = raw CGI::escapeHTML( fields )
#   html_options['href'] = '#'

#   content_tag(:a, name, html_options, &block)
# end
    
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bugs/_form.html.erb
    <%= form_with model: @bugs do |form| %>
      <p>
    <%= form.label :Title %><br>
    <%= form.text_field :title%>
    </p>

        <div class="field">
            <%= form.label :typeOf, class:"form-control" %><br />
            <%= form.select(:typeOf, Bug.typeOfs.keys.map {|role| [role.titleize,role]}) %>
          </div>

      <div class="field">
        <%= form.label :status_is, class:"form-control" %><br />
        <%= form.select(:status_is, Bug.status_is.keys.map {|role| [role.titleize,role]}) %>
      </div> 
      <p>
            <%= form.label :Project%><br>
            <%= form.collection_select(:project_id , Project.all, :id, :name, prompt: "Selcect Project") %><br>
            <br>
            <%= form.label :Creater%><br>
            <%= form.collection_select(:user_id , User.all, :id, :name, prompt: "Selcet User/Creater") %><br><br>
            <%= form.submit %>
      </p>

   <%end%>
   


  

app/views/bugs/edit.html.erb
<%=render "form" , bugs:@bugs%>

app/views/bugs/index.html.erb
<h1> Bugs
</h1>
<% @bugs.each do |b|%>
<%= link_to b.title,bug_path(b)%>
<br><br>
<%end%>

app/views/bugs/new.html.erb
<%=render "form" , bug:@bugs%>

app/views/bugs/show.html.erb
<h2>Bugs</h2>

 <div>

  <p>
    <strong>Title:</strong>
    <%= @bugs.title%>

  </p>
  <p>
    <strong>Bug_type:</strong>
    <%= @bugs.b_type %>
  </p> 
 <p>
<strong>Belongs_to project:</strong>
    <%= @bugs.project.name %>
  </p>   

 <p>
 <strong>Belongs_to creater:</strong>
    <%= @bugs.user.name %>
  </p>  
<p>
<%=link_to "edit " , edit_bug_path ,class:"btn btn-success"%>
 <%=link_to "delete" , bug_path(@bugs) ,data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  },class:"btn btn-danger" %> 

</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model:projects do |form| %>
<% if projects.errors.any? %>
   <div>
      <ul>
      <% projects.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <%= form.label :Project_Name%><br>
  <%= form.text_field :name, placeholder: "Project Title" %><br><br>
   <%= form.label :Project_Description%><br>
   <%= form.text_field :description, placeholder: "Project Description" %><br>
 
  <%= form.fields_for :project_users do |pu_form| %><br><br>


 <%=pu_form.collection_select(:user_id, User.all, :id, :name, prompt:"select Project")%>  <br><br>
<%
=begin%>
 <%= link_to_add_fields 'Add Product Variant', form, :user_id%> 
<%
=end%>

  <% end %>
  <%= form.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>edit project</h1>

<%=render "form" ,projects:@projects%>

app/views/projects/index.html.erb
<% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_in_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
  <%=flash[:error]%>
  <div class="container">
<h1 class="text-center text-primary">Projects</h1>
<div class="text-center"><%= form_tag(projects_path, method: "get") do %>
  <%= label_tag(:q, "Search project:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
  </div>  
<% end %>
<br><br>
<%if can? :create ,@projects%>
<%= link_to "add new project" ,new_project_path ,class:"btn btn-primary"%><br><br>
<%end%>
<%if @projects.present?%>

<% @projects.each do |p| %>
 
 <div> <h2>
    <%= link_to p.name,project_path(p) %>
  </h2>
 <% if can? :update , @projects %> 
 <p> <%=link_to "edit" , edit_project_path(p),class:"btn btn-success"%>
   <%end%>
    <% if can? :destroy , @projects %>
   <%= link_to "Delete", project_path(p) ,data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } ,class:"btn btn-danger"%> 
</p>
 <%end%>   
</div>
<%end%>
<%else%>
<br>
 <%=render plain:"no record found"%>
<% end %>
</div>

app/views/projects/new.html.erb
<h1>Create a new project</h1>

<%=render "form" ,projects:@projects%>

app/views/projects/show.html.erb
<h2> Project Details</h2>
<p> Praoject name :<%= @projects.name%></p>

<p>Description:  <%=@projects.description%></p>
<p>Users:<%@projects.users.each do |u|%>
<%= link_to u.name , user_path(u)%><br>
<%=link_to "delete user" , destroyUser_projects_path(u),data:{
    turbo_method:"delete",
    turbo_confirm: "Are you sure?"
    
},class:"btn btn-danger"%>
<br>
<%end%>
<p class="text-danger">Bugs:
</p>

<%@projects.bugs.each do |b|%>
<%= link_to b.title , bug_path(b)%>
<br>
<%end%>

<br>
<h2>Add a Bug</h2>

<%=link_to "add bug", new_bug_path ,class:"bt btn-primary"%>

   

app/views/users/index.html.erb
<h2> Welcome to BugTrackerApplication </h2>
<h2 >users
      </h2>
  <%@user.each do |u|%>
      <p>Name:<%= link_to u.name,user_path(u) %><br></p>
      <br><br><br>
      <%end%>
<% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to "Log out", log_out_path %>
      
   
      
      

  <% else %>
    <%= link_to "Sign up", sign_in_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
<p>


</p>

app/views/users/new.html.erb
<p>Already have an account? <%= link_to "log in", log_in_path %> </p>
<h2>Sign Up </h2>
<%= form_with model: @user do |u|%>
    <%if @user.errors.any?%>
    <div>
    <ul>
    <% @user.errors.full_messages.each do |m|%>
    <li><%=m%></li>
    <%end%></ul>
    </p>
    </div>
    <%end%>
<%=u.label:Name %><br>
<%=u.text_field:name %><br>
<%=u.label:Email%><br>
<%=u.text_field:email%><br>
<%=u.label:Password %><br>
<%=u.password_field:password %><br>
<%=u.label:ConfirmPassword %><br>
<%=u.password_field:password_confirmation %><br>
<%=u.label:User_type%><br>
<%=u.select(:user_type, options_for_select(User::USER_TYPE))%>
<%
=begin%>
 <%=u.select:user_type , options_for_select(User::USER_TYPE),{prompt:"select user type"}%><br><br> 
<%
=end%>
 <%
=begin%>
 <%= u.select :role, collection: User.roles.keys.to_a %> 
<%
=end%>


<%=u.submit:SignUp%>

<%end%>

app/views/users/show.html.erb
<h2>Description</h2>

<p> User name :<%= @users.name%></p>
<p> user email :<%= @users.email%></p>
<p> user type :<%= @users.user_type%></p>
<p> project name :<%@users.projects.each  do |p| %>
<%=p.name%>
<%end%></p>